id: P008149
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18775
  title: གྲོང་ཁྱེར་དང་གྲོང་གསེབ་ཀྱི་འཆར་གཞི་བཟོ་འགོད་བྱེད་ཕྱོགས་སྐོར་གྱི་ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་བཅའ་ཁྲིམས།
    དོན་འགྲེལ།
  author: ''
  volumes:
    486f9acd920f49a29b3f87a38efefa8f:
      image_group_id: I8LS18777
      title: ''
      volume_number: 1
      total_pages: 96
ebook_metadata:
  title: གྲོང་ཁྱེར་དང་གྲོང་གསེབ་ཀྱི་འཆར་གཞི་བཟོ་འགོད་བྱེད་ཕྱོགས་སྐོར་གྱི་ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་བཅའ་ཁྲིམས།
    དོན་འགྲེལ།
  author: ''
  sku: P008149
  cover: cover.jpg
  layers:
  - pagination
