id: opecha:P008149
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18775
  title: གྲོང་ཁྱེར་དང་གྲོང་གསེབ་ཀྱི་འཆར་གཞི་བཟོ་འགོད་བྱེད་ཕྱོགས་སྐོར་གྱི་ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་བཅའ་ཁྲིམས།
    དོན་འགྲེལ།
  volume: ''
  author: ''
